[project]
name = "Bootstrap"
revision = "1.0"

[profiles.default]
CONTEXT_SEVEN_API_KEY = { description = "API Key of context7", required = true }
GITHUB_API_KEY = {description = "API Key of github", required = true }

[profiles.local]

[profiles.development]
