package staff

// ID is a Staff aggregate identifier.
//
// Generated by idgen.NewFor[ID]() at command time; persisted as a
// UUIDv7 string. The typed alias prevents accidental cross-aggregate
// ID swaps at compile time.
//
// Cross-aggregate references to Staff IDs (e.g., the
// organization.Organization.ownerStaffID field) are stored as plain
// string to avoid circular imports between sibling domain packages.
// See docs/conventions/go/service-architecture.md for the rationale.
type ID string

// String implements fmt.Stringer.
func (id ID) String() string { return string(id) }
