package organization

// ID is an Organization aggregate identifier.
//
// Generated by idgen.NewFor[ID]() at command time; persisted as a
// UUIDv7 string. The typed alias prevents accidental cross-aggregate
// ID swaps at compile time — a value of staff.ID cannot be passed
// where organization.ID is expected.
//
// Cross-aggregate references to Organization IDs are stored as plain
// string in other aggregates (e.g., staff.Staff.organizationID) to
// avoid circular imports between sibling domain packages. See
// docs/conventions/go/service-architecture.md for the rationale.
type ID string

// String implements fmt.Stringer.
func (id ID) String() string { return string(id) }
