{ config, ... }:
let
  docsPort = 3000 + config.core.worktree.portOffset;
in
{
  languages = {
    javascript = {
      enable = true;
      npm = {
        enable = true;
      };
    };
  };
  scripts = {
    docs-install = {
      exec = ''
        cd "$WORKSPACE_ROOT" && npm install "$@"
      '';
      description = "Install workspace-docs npm dependencies";
    };
    docs-dev = {
      exec = ''
        cd "$WORKSPACE_ROOT" && npm run start -- --port ${toString docsPort} "$@"
      '';
      description = "Run the workspace docs site in dev mode (hot reload)";
    };
    docs-build = {
      exec = ''
        cd "$WORKSPACE_ROOT" && npm run build -- "$@"
      '';
      description = "Build the static workspace docs site into build/";
    };
    docs-serve = {
      exec = ''
        cd "$WORKSPACE_ROOT" && npm run serve -- --port ${toString docsPort} "$@"
      '';
      description = "Serve the built workspace docs site locally";
    };
  };
  core = {
    worktree = {
      enable = true;
    };
    ai = {
      claude = {
        enable = true;
      };
      opencode = {
        enable = true;
        profile = "slim";
      };
    };
    workspace = {
      enable = true;
      name = "workspace-docs";
      wsInfoDeepLevel = 2;
      treeInfos = {
        "README.md" = "Look at me first!";

        "docusaurus.config.ts" =
          "Docusaurus site config — two docs instances (workspace + portal) read sibling docs/ in place";
        "sidebarsWorkspace.ts" = "Autogenerated sidebar for workspace-wide docs (../../docs)";
        "sidebarsPortal.ts" = "Autogenerated sidebar for portal service docs (../../services/portal/docs)";

        "src" = "Site source — homepage and theme overrides";
        "src/pages" = "Standalone pages (homepage)";
        "src/css" = "Infima theme overrides";

        "static" = "Static assets served at site root";
      };
    };
    git = {
      enable = true;
    };
    toolchains = {
      markdown = {
        enable = true;
      };
    };
  };
}
